# Generated by Django 5.2.1 on 2025-05-31 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('pilot', 'Pilot'), ('cabin_crew', 'Cabin Crew'), ('operator', 'Airline Operator')], max_length=20)),
                ('is_active_duty', models.BooleanField(default=False)),
                ('duty_start_time', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('aircraft_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('haul_type', models.CharField(choices=[('short', 'Short Haul'), ('long', 'Long Haul'), ('both', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('weather', 'Weather Change'), ('gate', 'Gate Change'), ('departure', 'Departure Time Change'), ('duration', 'Flight Duration Change'), ('cancellation', 'Flight Cancellation'), ('crew', 'Crew Change')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_delivery_status', models.CharField(blank=True, max_length=20, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famadata.alert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='recipients',
            field=models.ManyToManyField(related_name='received_alerts', through='famadata.AlertRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CrewProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('captain', 'Captain'), ('first_officer', 'First Officer'), ('senior_cabin_crew', 'Senior Cabin Crew'), ('cabin_crew', 'Cabin Crew'), ('ground_crew', 'Ground Crew')], max_length=30)),
                ('seniority', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('training_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('instructor', 'Instructor')], max_length=20)),
                ('languages_spoken', models.JSONField(default=list)),
                ('preferred_haul', models.CharField(choices=[('short', 'Short Haul'), ('long', 'Long Haul'), ('both', 'Both')], max_length=10)),
                ('active_duty_days', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('standby_duty_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('reserve_duty_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('days_off', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('standby_start_time', models.TimeField(default='08:00:00')),
                ('standby_end_time', models.TimeField(default='20:00:00')),
                ('reserve_start_time', models.TimeField(default='08:00:00')),
                ('reserve_end_time', models.TimeField(default='20:00:00')),
                ('allow_swapping', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FatigueLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duty_start', models.DateTimeField()),
                ('duty_end', models.DateTimeField(blank=True, null=True)),
                ('total_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('flight_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fatigue_level', models.CharField(choices=[('green', 'Legal to Fly'), ('orange', 'Warning'), ('red', 'Needs Rest')], default='green', max_length=10)),
                ('rest_required_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='famadata.flight'),
        ),
        migrations.CreateModel(
            name='FlightSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_swaps', to=settings.AUTH_USER_MODEL)),
                ('requesting_crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requesting_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_from', to='famadata.flight')),
                ('target_crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL)),
                ('target_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_to', to='famadata.flight')),
            ],
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duty_date', models.DateField()),
                ('duty_type', models.CharField(choices=[('active', 'Active Duty'), ('standby', 'Standby'), ('reserve', 'Reserve'), ('off', 'Off Duty')], max_length=20)),
                ('duty_start_time', models.DateTimeField()),
                ('duty_end_time', models.DateTimeField()),
                ('position', models.CharField(choices=[('captain', 'Captain'), ('first_officer', 'First Officer'), ('senior_cabin_crew', 'Senior Cabin Crew'), ('cabin_crew', 'Cabin Crew'), ('ground_crew', 'Ground Crew')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rosters', to=settings.AUTH_USER_MODEL)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='famadata.flight')),
            ],
            options={
                'unique_together': {('crew_member', 'duty_date')},
            },
        ),
    ]
