# Generated by Django 5.2.1 on 2025-06-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
